### ISSUE TITLE
Using normal constraints yields strange results

### ISSUE THREAD

**Issue by majia67** [NYUGeometricModeling/GM_Assignment_2#2]
I'm trying to implement Chen Shen's paper about the normal constraints. I got the following result when trying to render the bunny:

![image](https://user-images.githubusercontent.com/11867815/37115615-953fdfa8-2219-11e8-98e7-cabfd35bdcef.png)

This phenomenon is only observed when using poly degree = 1 or 2. I did connected components filtering.

What might be the reason?

**Comment by danielepanozzo** [comment]
Very strange, can you check the residual of your linear system solve to make sure that the linear solver is working correctly? Could it be that you have an undetermined system for higher poly degree since you are not gathering enough points?

**Comment by majia67** [comment]
I have an error report for residuals bigger than 0.1, so it's not likely. I think it's very likely your second reason. After trying a mesh with much denser point cloud, such phenomenon disappeared.

![image](https://user-images.githubusercontent.com/11867815/37190295-11483de4-2327-11e8-8a16-92a15dcccc11.png)
