### ISSUE TITLE
Submitting the assignment issues

### ISSUE THREAD

**Issue by abhijit-c** [NYUGeometricModeling/GM_Assignment_2#3]
Hello all,

Finally am done with my assignment, ready to go ahead and submit it. I was looking over the Submitting section of the README and it states to follow the link sent out by the TA (presumably to create the private repository to send work in the organization it talks about). However, I can't find said link it mentions? 

Apologies, I am new to github's organization system and probably should have figured this out with assignment 1.

**Comment by jiangzhongshi** [comment]
Hi,

The link is https://classroom.github.com/a/TJmhsxoo

If you haven’t received my emails, please let me know.

Best,
Zhongshi
