### ISSUE TITLE
CMake error without changing the code

### ISSUE THREAD

**Issue by sysumathcoder** [NYUGeometricModeling/GM_Assignment_2#4]
Hi,

When I try to run cmake .. under build directory, there are errors as shown below. But I run hw1 successfully, do you have any tips to solve it, thanks!:

`CMake Deprecation Warning at external/libigl/external/glfw/CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using Cocoa for window creation
-- Creating target: igl::opengl_glfw_imgui (igl_opengl_glfw_imgui)
fatal: bad object bc6ac8b2aee0614debd940e45bc9cd0d9b355c86
fatal: reference is not a tree: bc6ac8b2aee0614debd940e45bc9cd0d9b355c86
CMake Error at /Geometric Modeling/gm-assignment-2-sysumathcoder/external/libigl/external/.cache/imgui/imgui-download-prefix/tmp/imgui-download-gitupdate.cmake:147 (message):
  Failed to checkout tag: 'bc6ac8b2aee0614debd940e45bc9cd0d9b355c86'

make[2]: *** [imgui-download-prefix/src/imgui-download-stamp/imgui-download-update] Error 1
make[1]: *** [CMakeFiles/imgui-download.dir/all] Error 2
make: *** [all] Error 2
CMake Error at cmake/DownloadProject.cmake:179 (message):
  Build step for imgui failed: 2
Call Stack (most recent call first):
  external/libigl/cmake/LibiglDownloadExternal.cmake:14 (download_project)
  external/libigl/cmake/LibiglDownloadExternal.cmake:86 (igl_download_project)
  external/libigl/cmake/libigl.cmake:363 (igl_download_imgui)
  cmake/FindLIBIGL.cmake:37 (include)
  CMakeLists.txt:38 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Geometric Modeling/gm-assignment-2-sysumathcoder/build/CMakeFiles/CMakeOutput.log".`

**Comment by jiangzhongshi** [comment]
Hi,

The cmake system should be the same. Can you remove everything inside external/ and build/, to try again?

**Comment by sysumathcoder** [comment]
It works after removing external/..., thank you so much
